<a href="https://colab.research.google.com/github/Yseokjun/2026-2-BDA-/blob/main/6w_dataframe_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import pandas as pd
import numpy as np

In [102]:
# dict

In [103]:
df = pd.DataFrame([{'국어': 70, '수학': 89, '영어': 90},
                   {'국어': 80, '영어':99},
                   {'수학': 66, '영어': 78}])
df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [104]:
s1 = pd.Series([90,80,60, 66])
s2 = pd.Series([45, 73, 83, 99,])
s3 = pd.Series([92, 75, 82, 75])
s1

0    90
1    80
2    60
3    66
dtype: int64

In [105]:
df = pd.DataFrame({'국어':s1, '영어':s2, '수학':s3})
df

   국어  영어  수학
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [106]:
df.index = ['노', '장','박' ,'강']
df

   국어  영어  수학
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [107]:
# NaN 표시

In [108]:
df = pd.DataFrame({'A':pd.Series([10,20,30], index=[0,1,2]),
                   'B':pd.Series([3,2,1], index=[1,2,3])})
df

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [109]:
s1 = pd.Series([90,80,60], index=['노', '창', '박'])
s2 = pd.Series([45, 73, 99], index=['장', '박', '강'])
s3 = pd.Series([92, 75, 82,75])

In [110]:
df = pd.DataFrame({'국어':s1, '영어':s2, '수학':s3},
                  index = ['노', '장', '박', '강'])
df

     국어    영어  수학
노  90.0   NaN NaN
장   NaN  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [111]:
# df.dtypes

In [112]:
d = {'col1': [1,2], 'col2':[3,4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [113]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [114]:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [115]:
# 여러날짜 시퀀스 date_range

In [116]:
dates = pd.date_range("20250101", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [117]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [118]:
dates = pd.date_range("20250101", end= '20250110')
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [119]:
# freq=3D

In [120]:
dates = pd.date_range("20250101", periods=6, freq="3D")
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [121]:
dates = pd.date_range("20250101", periods=6, freq="3H")
dates

/tmp/ipykernel_4647/2595638508.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq="3H")

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [122]:
dates = pd.date_range("20250101", periods=6, freq="w")
dates

/tmp/ipykernel_4647/2192658039.py:1: FutureWarning: 'w' is deprecated and will be removed in a future version, please use 'W' instead.
  dates = pd.date_range("20250101", periods=6, freq="w")

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [123]:
dates = pd.date_range("20260101", periods=6, freq="W-SUN")
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [124]:
# freq=W-TUE

In [125]:
dates = pd.date_range("20260101", periods=6, freq="W-FRI")
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [126]:
dates = pd.date_range("20250101", periods=6, freq="M")
dates

/tmp/ipykernel_4647/837797980.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq="M")

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [127]:
dates = pd.date_range("20250101", periods=6, freq="MS")
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [128]:
# 날씨를 포함ㅎ나 데이터프레임

In [129]:
date = pd.date_range("20250302", periods=6)
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [130]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-01-01  0.288902 -1.671863 -0.239464  0.247749
2025-02-01 -0.869298  1.419324  0.680888  0.881191
2025-03-01  0.530445 -0.204576  0.814361 -0.213567
2025-04-01 -0.190334 -0.678837  1.872619 -0.120538
2025-05-01  1.154949  0.578575  0.197078 -0.408345
2025-06-01  1.580367  0.225081 -1.035895 -0.492711

In [131]:
# 다양한 자료형으로 구성된 데이터 프레임

In [132]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20250302"),
    "C": pd.Series(np.arange(1,3,.5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
    })
df

                   A         B         C         D
2025-01-01  0.288902 -1.671863 -0.239464  0.247749
2025-02-01 -0.869298  1.419324  0.680888  0.881191
2025-03-01  0.530445 -0.204576  0.814361 -0.213567
2025-04-01 -0.190334 -0.678837  1.872619 -0.120538
2025-05-01  1.154949  0.578575  0.197078 -0.408345
2025-06-01  1.580367  0.225081 -1.035895 -0.492711

In [133]:
# dataframe의 다양한 참조

In [134]:
pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index= ['윤일형', '강수희','홍소희','유한빈','신수빈'],
                  columns=['중간','기말','과제','출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [135]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [136]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [137]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [138]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [139]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [140]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [141]:
# 조건의 맞는행 참조

In [142]:
pf['중간'] >20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [143]:
# pf.loc

In [144]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [145]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [146]:
pf[(pf['출석'] >=19) & (pf['기말'] >=20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [147]:
# df.loc

In [148]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [149]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [150]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [151]:
pf.loc['윤일형' : '유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [152]:
pf.loc[pf.중간> 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [153]:
pf.loc[(pf.중간 >10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [154]:
# loc[index[i]]로 행참조

In [155]:
pf.loc[pf.index[0]]

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [156]:
pf.loc[[pf.index[0]]]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [157]:
pf.loc[pf.index[1:4]]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [158]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [159]:
## 열참조

In [160]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [161]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [162]:
pf.loc[:,['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [163]:
##loc열 참조

In [164]:
pf.loc[:, pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [165]:
pf.loc[:, [pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [166]:
pf.loc[:, pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [167]:
pf.loc[:, pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [168]:
pf.loc[:, pf.columns[1:]][['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [169]:
# 행과 열 참조

In [170]:
pf.loc['윤일형', '출석']

np.int64(18)

In [171]:
pf.loc['윤일형': '유한빈','기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [172]:
pf.loc['윤일형': '유한빈','기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [173]:
pf.loc[pf.index[0], pf.columns[1]]

np.int64(35)

In [174]:
pf.loc[pf.index[0:3], pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [175]:
pf.loc[pf.index[0:3], pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

In [176]:
# df.iloc

In [177]:
pf.iloc[:,2]

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [178]:
pf.iloc[:,[2]]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [179]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [180]:
pf.iloc[1,1]

np.int64(27)

In [181]:
pf.iloc[1:3,1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [182]:
pf.iloc[:,1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [183]:
pf.iloc[[1,3,4], 1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [184]:
pf.iloc[[1,3,4], [0,1]]

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [185]:
# at

In [186]:
pf.at['윤일형', '과제']

np.int64(8)

In [187]:
pf.at['유한빈', '기말']

np.int64(22)

In [188]:
pf.at[pf.index[1], '출석']

np.int64(20)

In [189]:
pf.at[pf.index[3],pf.columns[2]]

np.int64(9)

In [190]:
# iat

In [191]:
pf.iat[1,2]

np.int64(10)

In [192]:
pf.iat[2,3]

np.int64(19)

In [193]:
# 데이터프레임 정보와 조건 검색

In [194]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [195]:
df.describe() # 기초적 통계량

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [196]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [197]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 684.0+ bytes

In [199]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [200]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [201]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [202]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [203]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [204]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [205]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [206]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [207]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [208]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [209]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [210]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [211]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [212]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [213]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [214]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [215]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [216]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [217]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [218]:
df2 > 10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [219]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [220]:
df2[ [True]*6 + [False]*7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [221]:
df2[ '재해자수'] >400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [222]:
df2[df2['재해자수'] >400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [223]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [224]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [225]:
df['사망(명)'].isin([7,10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [226]:
df[df['사망(명)'].isin([7,10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [227]:
df[(df['사망(명)'].isin([7,10])) | (df['사망(명)'] > 350)]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367